### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by go-lx** [cksidharthan/go-bybit#26]
I see that the API related to placing an order is not implemented. It is recommended to expose transport.Http object so that users can realize some functions they do not have!!

<img width="720" alt="image" src="https://user-images.githubusercontent.com/35762503/189547289-4d3560b4-a4c7-4251-983a-a2b8986d1215.png">

**Comment by cksidharthan** [comment]
@go-lx - thanks for pointing it out. I've fixed it now in #27. [[release v0.0.5](https://github.com/cksidharthan/go-bybit/releases/tag/v0.0.5)]😄 
one more thing, I have placing order endpoint implemented for Linear and Spot if that's what you are using. 👍🏻

**Comment by cksidharthan** [comment]
fixed in #27
